#pragma once

#define UM_STATISTIC WM_USER + 1
#define UM_ALERT WM_USER + 2
#define UM_VOLTAGE WM_USER + 3
#define UM_VOLTAGERANK WM_USER + 4
#define UM_WARNINGRANK WM_USER + 5
#define UM_LOADVINS WM_USER + 6
#define UM_QUERYVINS WM_USER + 7
#define UM_REFRESHREC WM_USER + 8
#define UM_DESTROYHISTORYDLG WM_USER + 9
#define UM_YESTODAYREC WM_USER + 10
#define UM_LASTWEEKREC WM_USER + 11
#define UM_MILEAGERANK WM_USER + 12

#define NETWORK_EVENT WM_USER + 20